### ISSUE TITLE
rCharts2 will have dimple included

### ISSUE THREAD

**Issue by timelyportfolio** [jpmarindiaz/dimpler#1]
Perfectly fine to do you own `dimple` widget, but just so you know, the up and coming `rCharts2` from @ramnathv will include full support for `dimple`.

**Comment by jpmarindiaz** [comment]
Sounds great, looking forward to take a look. 
I am experimenting with something more out of the box plotting widget exclusive for dimple. Cheers

**Comment by timelyportfolio** [comment]
in case you are interested, here is the version I mentioned http://www.buildingwidgets.com/blog/2015/3/18/week-11-dimple-as-htmlwidget

**Comment by happyshows** [comment]
@timelyportfolio Is there any estimated release date for rCharts2?

**Comment by ramnathv** [comment]
@happyshows Most likely `rCharts2` will be released as a set of packages, all following the same consistent syntax. `rcdimple` is the first we released, and the others are coming soon.

**Comment by happyshows** [comment]
@ramnathv  is it possible to add a standard navr toolbar (similar to rbokeh toolbar) across all rcharts2 package? In my implementation, user constantly ask for export, zoom-in/out, drag features.

http://www.buildingwidgets.com/blog/2015/3/11/week-10-responsive-toolbars

**Comment by ramnathv** [comment]
@happyshows Doing that across libraries would be pretty hard given how different implementations are. I am exploring ways to do an SVG export generically, and that is something that can be added. Other features like zoom/drag etc. are a lot tougher to do in a generic manner.

**Comment by jcheng5** [comment]
@ramnathv Just in case you haven't played much with it, the bokeh zoom/drag is way better than just doing SVG; the axes scales adapt with the current view, and the text stays at the appropriate size. (Not that SVG export isn't still generally useful...)

**Comment by ramnathv** [comment]
Thanks @jcheng5 . I have played with it and it is good. But implementing something like that across viz libraries is hard.
